### ISSUE TITLE
PHP 8.4: Crash/Segfault when using zRange/zRangeByScore with WITHSCORES option

### ISSUE THREAD

**Issue by bluestonev** [phpredis/phpredis#2791]
### Expected behaviour
`zRange` and `zRangeByScore` with `['WITHSCORES' => true]` option should return an associative array of members with their scores.

### Actual behaviour
PHP crashes (segfault/timeout) when calling these methods with WITHSCORES option on PHP 8.4.

### Environment
- **OS**: Alpine Linux (Docker)
- **PHP**: 8.4.3
- **phpredis**: 6.2.0 / 6.3.0
- **Redis Server**: 7.2.5

### Steps to reproduce
```php
<?php
$redis = new Redis();
$redis->connect('127.0.0.1', 6379);

// Add test data
$redis->zAdd('test_key', 1, 'member1');
$redis->zAdd('test_key', 2, 'member2');

// This works fine
var_dump($redis->zRange('test_key', 0, -1));

// This crashes PHP
var_dump($redis->zRange('test_key', 0, -1, ['WITHSCORES' => true]));

// This also crashes
var_dump($redis->zRangeByScore('test_key', '-inf', '+inf', ['withscores' => true]));

// rawCommand also crashes or timeouts
var_dump($redis->rawCommand('ZRANGE', 'test_key', 0, -1, 'WITHSCORES'));
```

### Workaround
Currently using `eval()` as a workaround:
```php
$script = "return redis.call('ZRANGE', KEYS[1], ARGV[1], ARGV[2], 'WITHSCORES')";
$result = $redis->eval($script, [$key, 0, -1], 1);
```

### Additional notes
- Works fine on PHP 8.3 + phpredis 6.x
- `zRange` without WITHSCORES works fine on PHP 8.4
- Other methods like `get`, `set`, `hGet` work fine
- Setting `OPT_SERIALIZER` or `OPT_COMPRESSION` does not affect the issue

### Related
This may be related to the PHP 8.4 internal changes. Similar issues were fixed in:
- #2649 (SIGABRT fix for RedisArray)
- c139de3 (PHP 8.4 compilation error fix)

**Comment by yatsukhnenko** [comment]
@bluestonev I can't replicate the issue locally

```bash
/phpredis # cat /etc/os-release 
NAME="Alpine Linux"
ID=alpine
VERSION_ID=3.23.2
PRETTY_NAME="Alpine Linux v3.23"
HOME_URL="https://alpinelinux.org/"
BUG_REPORT_URL="https://gitlab.alpinelinux.org/alpine/aports/-/issues"
/phpredis # php --ri redis

redis

Redis Support => enabled
Redis Version => 6.3.0
Redis Sentinel Version => 1.0
Git revision => $Id: df4fab2de7fc327c54c94a13af2b9542e4fbd720 $
Available serializers => php, json

Directive => Local Value => Master Value
redis.arrays.algorithm => no value => no value
redis.arrays.auth => no value => no value
redis.arrays.autorehash => 0 => 0
redis.arrays.connecttimeout => 0 => 0
redis.arrays.distributor => no value => no value
redis.arrays.functions => no value => no value
redis.arrays.hosts => no value => no value
redis.arrays.index => 0 => 0
redis.arrays.lazyconnect => 0 => 0
redis.arrays.names => no value => no value
redis.arrays.pconnect => 0 => 0
redis.arrays.previous => no value => no value
redis.arrays.readtimeout => 0 => 0
redis.arrays.retryinterval => 0 => 0
redis.arrays.consistent => 0 => 0
redis.clusters.cache_slots => 0 => 0
redis.clusters.auth => no value => no value
redis.clusters.persistent => 0 => 0
redis.clusters.read_timeout => 0 => 0
redis.clusters.seeds => no value => no value
redis.clusters.timeout => 0 => 0
redis.pconnect.pooling_enabled => 1 => 1
redis.pconnect.connection_limit => 0 => 0
redis.pconnect.echo_check_liveness => 1 => 1
redis.pconnect.pool_detect_dirty => 0 => 0
redis.pconnect.pool_poll_timeout => 0 => 0
redis.pconnect.pool_pattern => no value => no value
redis.session.locking_enabled => 0 => 0
redis.session.lock_expire => 0 => 0
redis.session.lock_retries => 100 => 100
redis.session.lock_wait_time => 20000 => 20000
redis.session.lock_failure_readonly => 0 => 0
redis.session.early_refresh => 0 => 0
redis.session.compression => none => none
redis.session.compression_level => 3 => 3
/phpredis # php debug.php 
array(2) {
  [0]=>
  string(7) "member1"
  [1]=>
  string(7) "member2"
}
array(2) {
  ["member1"]=>
  float(1)
  ["member2"]=>
  float(2)
}
array(2) {
  ["member1"]=>
  float(1)
  ["member2"]=>
  float(2)
}
array(4) {
  [0]=>
  string(7) "member1"
  [1]=>
  string(1) "1"
  [2]=>
  string(7) "member2"
  [3]=>
  string(1) "2"
}
```

Could you provide your Dockerfile or additional steps to reproduce issue?

**Comment by bluestonev** [comment]
php docker image 8.4.3-fpm-alpine3.21

Could you please test with LZF compression and PHP serializer enabled?

$redis->setOption(Redis::OPT_COMPRESSION, Redis::COMPRESSION_LZF);
$redis->setOption(Redis::OPT_SERIALIZER, Redis::SERIALIZER_PHP);

**Comment by michael-grunder** [comment]
What's weird about this is that `rawCommand` uses a completely different path and won't uncompress or deserialize the data.

Can you provide the `Dockerfile` itself?

**Comment by bluestonev** [comment]
I am not saying that rawCommand doesn't work. What I'm reporting is that zRange, zRangeByScore, zRevRange, and zRevRangeByScore crash when called with the option ['WITHSCORES' => true], using LZF compression and PHP serializer.

**Comment by michael-grunder** [comment]
Can you give me a Dockerfile that replicates the crash so I can build and run it?

I have run your script in that exact docker container and do not see a crash, but I don't know if there is anything else different about how you are building PhpRedis. It's hard to fix a problem we can't replicate.

**Comment by bluestonev** [comment]
### Environment

**Dockerfile:**
```dockerfile
FROM php:8.4.3-fpm-alpine3.21
RUN apk add --no-cache ${PHPIZE_DEPS}

RUN pecl install lzf && \
    docker-php-ext-enable lzf

RUN pecl install -o -f -D 'enable-redis-lzf="yes"' redis && \
    docker-php-ext-enable redis
```

### Issue

When using `OPT_COMPRESSION` with `COMPRESSION_LZF`, calling `zRangeByScore` with `['WITHSCORES' => true]` causes a crash.
```php
$redis->setOption(PhpRedis::OPT_SERIALIZER, PhpRedis::SERIALIZER_PHP);
$redis->setOption(Redis::OPT_COMPRESSION, Redis::COMPRESSION_LZF);
$redis->zRange($key, 0, -1, ['WITHSCORES' => true]);  // Crash
```

### Expected behavior

The command should return an associative array of members with their scores.

### Actual behavior

PHP crashes when `OPT_COMPRESSION` is set to `COMPRESSION_LZF`.

Without the compression option, it works fine:
```php
$redis->setOption(PhpRedis::OPT_SERIALIZER, PhpRedis::SERIALIZER_PHP);
// $redis->setOption(Redis::OPT_COMPRESSION, Redis::COMPRESSION_LZF);  // Disabled
$redis->zRange($key, 0, -1, ['WITHSCORES' => true]);  // Works
```

### Summary

- ✅ Works: Without `OPT_COMPRESSION`
- ❌ Crash: With `OPT_COMPRESSION` set to `COMPRESSION_LZF`

Thank you for your time and for maintaining this great library.

**Comment by michael-grunder** [comment]
I was able to find a `ZRANGE` segfault in PhpRedis but it had to do with serialization not compression.

I have created a [reproducer repo here](https://github.com/michael-grunder/phpredis-zrange-reproducer). 

This script executes normally and does not crash, whether I enable compression or not. If you rework the php script in such a way that PhpRedis crashes, just open a PR and then I can take a look.

**Comment by bluestonev** [comment]
The key difference is using **integer values as members** instead of strings.

```php
<?php
$redis = new Redis();
$redis->connect('127.0.0.1', 6379);
$redis->setOption(Redis::OPT_SERIALIZER, Redis::SERIALIZER_PHP);
$redis->setOption(Redis::OPT_COMPRESSION, Redis::COMPRESSION_LZF);

// Using integers as members (not strings)
$redis->zAdd('test_key', 1, 1);
$redis->zAdd('test_key', 2, 2);

// OK
var_dump($redis->zRange('test_key', 0, -1));

// SEGFAULT
var_dump($redis->zRange('test_key', 0, -1, ['WITHSCORES' => true]));
```

Works (no crash): `$redis->zAdd('test_key', 1, 'member1');`

Crashes: `$redis->zAdd('test_key', 1, 1);`

It seems the crash occurs when the serialized integer member is decompressed with WITHSCORES option.

**Comment by michael-grunder** [comment]
Perfect, then my merged PR should fix this. That was the flaw I fixed

**Comment by michael-grunder** [comment]
Closing via #2793
