### ISSUE TITLE
Compilation error: 'void *': unknown size

### ISSUE THREAD

**Issue by Jan-E** [phpredis/phpredis#1514]
On Windows (VC14, PHP 7.0 x86 ZTS) php_redis.dll fails to compile:

> ext\redis\library.c(1899): error C2036: 'void *': unknown size
> NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\cl.exe"' : return code '0x2'
> Stop.

The offending line 1899 was introduced in the commit https://github.com/phpredis/phpredis/commit/c76e00fb25a005dc80d3e1d1ea2d64626ab155c2?_pjax=%23js-repo-pjax-container by @yatsukhnenko 

I did not yet check things like VC15 PHP 7.3 x64 NTS

**Comment by Jan-E** [comment]
The same error occurred in VC15 PHP 7.3 x64 NTS

**Comment by michael-grunder** [comment]
Yeah sizeof(void*) isn't standard but will compile with gcc.  I'll change it to char* when I'm at a computer.

**Comment by Jan-E** [comment]
It was the next line that caused the error:
`le = (void *)l + sizeof(*l);`
TIA for fixing

**Comment by Jan-E** [comment]
Changing both instances fixes the compilation error:
```
diff --git a/library.c b/library.c
index 73f22da..0b87b18 100644
--- a/library.c
+++ b/library.c
@@ -1895,8 +1895,8 @@ redis_sock_disconnect(RedisSock *redis_sock, int force TSRMLS_DC)
                 zend_resource *le = zend_hash_find_ptr(&EG(persistent_list), persistent_id);
                 if (!le) {
                     zend_llist *l = pecalloc(1, sizeof(*l) + sizeof(*le), 1);
-                    zend_llist_init(l, sizeof(void *), NULL, 1);
-                    le = (void *)l + sizeof(*l);
+                    zend_llist_init(l, sizeof(char *), NULL, 1);
+                    le = (char *)l + sizeof(*l);
                     le->type = le_redis_pconnect;
                     le->ptr = l;
                     zend_hash_str_update_mem(&EG(persistent_list), ZSTR_VAL(persistent_id), ZSTR_LEN(persistent_id), le, sizeof(*le));

```

**Comment by yatsukhnenko** [comment]
@Jan-E I pushed the fix to `develop` branch. Could you test it?

**Comment by Jan-E** [comment]
I tested the 2 extremes: VC14 PHP 7.0.33 x86 TS and VC15 PHP 7.3.3RC1 x64 NTS. Both compile fine.
