### ISSUE TITLE
Compile error when build on Windows with php 5.5 and  phpredis 2.2.4(pecl)

### ISSUE THREAD

**Issue by ixpress** [phpredis/phpredis#383]
When I try to buid php 5.5 and phpredis 2.2.4(pecl) x64 on windows,
I got some errors.

First, I got error like this: "NMAKE : fatal error U1073: don't know how to make '..\pecl\redis\igbinary\hash_function.c'".
I checked "redis" dir, and there doesn't have the "igbinary" dir, so I checked the "config.w32", and get "igbinary", and put it in the "redis" dir.

After this, I try to buid it again, while got error like this: "fatal error C1083 cannot open compiler generated file:'x64\Release_TS\pecl\redis\igbinary\hash_function.obj': No such file or directory".

Does anyone build on Windows with php 5.5 and  phpredis 2.2.4(pecl) succeed?

**Comment by michael-grunder** [comment]
Closing very old issues.  This was fixed and PHP is now on 7.x.x
