### ISSUE TITLE
phpredis-3.1.0 fails to build with php-5.2.17

### ISSUE THREAD

**Issue by sergey-dryabzhinsky** [phpredis/phpredis#1065]
Compilation error:
```
In file included from /home/sergey/debuild-php/modules/php-mod-redis/php-mod-redis-3.1.0/src/redis_commands.h:4:0,                                                                                            
                 from /home/sergey/debuild-php/modules/php-mod-redis/php-mod-redis-3.1.0/src/redis_commands.c:25:                                                                                             
/home/sergey/debuild-php/modules/php-mod-redis/php-mod-redis-3.1.0/src/common.h:69:1: error: unknown type name ‘zend_always_inline’                                                                           
 static zend_always_inline zval *                                                                                                                                                                             
 ^ 
```

System: Ubuntu 14.04 amd64 updated
GCC: 4.8.4
PHP: 5.2.17

I know that php version is long time forgotten, outdated, not supported.

So, maybe phpredis should officialy drop support of php-5.2 since 3.1?
Provide package.xml for PECL archive with php-5.3+ defined support?
And keep php-5.2 for phpredis-2.2.8.

**Comment by sergey-dryabzhinsky** [comment]
I have a fix for this.
Soon I'll make PR.

**Comment by sergey-dryabzhinsky** [comment]
Done in #1066

**Comment by michael-grunder** [comment]
@sergey-dryabzhinsky Thanks for the report!  If it's a simple enough that'll make it work in php 5.2 that's fine with me.  On the other hand, if it's all that complicated I am also totally fine with deprecating php 5.2.  It's > 10 years old :smiley_cat:

**Comment by sergey-dryabzhinsky** [comment]
Well, I don't have any project which need redis and php-5.2.
All of them are php-5.5+.
And not many people have such setup.
So, deprecating support of php-5.2 will be fine I think.

**Comment by michael-grunder** [comment]
Thanks for the PR!

**Comment by yatsukhnenko** [comment]
I belive that we should drop php5.2 support

**Comment by michael-grunder** [comment]
I think so too.  5.2. isn't supported anymore (for a long time now).  Happy to reexamine if there is a compelling reason.

Closing this issue.
